name: Ubuntu - SSH Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Essentials
        run: |
          sudo apt update
          sudo apt install -y openssh-server

      - name: Start SSH Server
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "SSH Server Started"

      - name: Install Ngrok for Tunneling
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Expose SSH via Ngrok
        run: |
          nohup ngrok tcp 22 &  # Memulai tunneling pada port 22 untuk SSH
          sleep 5  # Tunggu Ngrok memulai tunneling
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ssh_url.txt
          echo "Ngrok tunnel URL untuk SSH tersedia di ssh_url.txt"

      - name: Display SSH Access Information
        run: |
          echo "SSH URL:"
          cat ssh_url.txt
        # Anda juga bisa menyimpan URL SSH ini sebagai artifact atau mengirimnya melalui notifikasi.
