name: Ubuntu - SSH Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Essentials
        run: |
          sudo apt update
          sudo apt install -y openssh-server

      - name: Start SSH Server
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Install Ngrok for Tunneling
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: |
          ngrok authtoken "r99U4padYPE8 "  # Ganti dengan token Anda
          
      - name: Expose SSH via Ngrok
        run: |
          nohup ngrok tcp 22 &
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ssh_url.txt
          echo "Ngrok tunnel URL untuk SSH tersedia di ssh_url.txt"
